Fix potential Null pointer dereference in bench_httpclient.c
libevent/libevent pull request #1609
Opened 2024-04-10 10:03 UTC by icy17

2024-04-15 07:19 UTC, azat commented on test/bench_httpclient.c
> +		return -1;
Should close the fd as well, and also let's improve the caller to print which request failed

2024-04-22 07:57 UTC, icy17 commented
I just add cleanup, but I'm not sure how to "print which request failed" :(

2024-04-29 05:56 UTC, azat requested changes
>I just add cleanup, but I'm not sure how to "print which request failed" :(

Replace `perror("launch")` with `fprintf(stderr, "Cannot launch %i requet\n", i);` and can you also please add an error path into main

2024-06-23 19:15 UTC, azat commented
Merged https://github.com/libevent/libevent/pull/1676 with co-authorship instead. Thank you for you work.

2024-06-23 19:15 UTC, closed without merging