Use evutil_socket_t instead in http server sample and handle 64 bit Windows
libevent/libevent pull request #1682
Opened 2024-06-24 08:47 UTC by Coeur

Fixes #1574.
Supersedes #1575.

2024-06-24 08:50 UTC, azat reviewed
OK. BTW signals are not supported on windows, so let's just hide this code under `#ifndef _WIN32`?

2024-06-24 14:13 UTC, Coeur commented
But which part of the code (which line numbers) ?
And if the file is currently compiling fine, why adding macros that would complexify the file?

2024-06-26 04:11 UTC, azat commented
> And if the file is currently compiling fine, why adding macros that would complexify the file?

To avoid readers of this file think that signals is supported on windows

2024-06-26 04:17 UTC, azat commented
Hm, actually, [windows does support signals](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-170), but they are not asynchronous, plus SIGINT creates a thread - very odd

2024-06-26 04:18 UTC, azat commented
It is ok to leave as-is, but the codes does not compile. Please fix

```
http-server.obj : error LNK2019: unresolved external symbol strsignal referenced in function do_term [D:\a\libevent\libevent\build\http-server.vcxproj]
D:\a\libevent\libevent\build\bin\Debug\http-server.exe : fatal error LNK1120: 1 unresolved externals [D:\a\libevent\libevent\build\http-server.vcxproj]
```

2024-06-26 04:19 UTC, azat requested changes
.

2024-06-29 13:51 UTC, azat commented on util-internal.h
> +#define strsignal(sig) "Signal"
Inline function is prefered over macroses

2024-06-29 14:10 UTC, azat approved these changes

2024-07-08 08:10 UTC, merged